### ISSUE TITLE
Keep login state after refresh

### ISSUE THREAD

**Issue by rubensworks** [SolidLabResearch/solid-todo-app-vue#2]
After logging in once, and refreshing the page, the user should still be logged in.

**Comment by surilindur** [comment]
This has still not been implemented, because the Inrupt library used for logging in and out does not expose the authorization token value that could be saved to a cookie and read from it. There was some discussion about it, and exposing that to the application code might be a security concern, which is why it has not been done? But it should be doable somehow, I think. Maybe another library needs to be used, or another approach entirely.

**Comment by rubensworks** [comment]
Have a look at comunica's jquery widget, there the option is enabled.

**Comment by surilindur** [comment]
It turned out it was just one configuration option, and the Inrupt library handles restoring the session on its own. This is fixed now.
