### ISSUE TITLE
Cleanup code

### ISSUE THREAD

**Issue by rubensworks** [SolidLabResearch/solid-todo-app-vue#4]
Some suggestions for code improvements:

* [ ] Remove dead code: Instead of commenting out code, it should be removed. If needed, we can still recover it from the git commit history
* [ ] Remove `console.log` statements. It's ok to use them for debugging, but they must be removed before each commit.

**Comment by surilindur** [comment]
Both tasks have been done, with the exception of the ACL entry deletion code, that is left there as commented, because it works but produces permission issues as a side effect. When deleting all data from a file in a Solid pod (through a SPARQL query), the empty file is left in place. The CSS reports that file as being there, so Comunica attempts to fetch it, and removing the ACL entry produces an error when doing that.

I think the files themselves should probably somehow be deleted when all their contents are removed, but it is beyond the scope of this issue, maybe? :thinking:
